# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: ayundina <marvin@codam.nl>                   +#+                      #
#                                                    +#+                       #
#    Created: 2019/02/07 12:38:25 by ayundina      #+#    #+#                  #
#    Updated: 2019/06/03 13:06:14 by ayundina      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = libftprintf.a

SRCS = ft_atoi.c \
	   ft_bzero.c \
	   ft_isalnum.c \
	   ft_isalpha.c \
	   ft_isascii.c \
	   ft_isdigit.c \
	   ft_isprint.c \
	   ft_itoa.c \
	   ft_memalloc.c \
	   ft_memccpy.c \
	   ft_memchr.c \
	   ft_memcmp.c \
	   ft_memcpy.c \
	   ft_memdel.c \
	   ft_memmove.c \
	   ft_memset.c \
	   ft_putchar_fd.c \
	   ft_putchar.c \
	   ft_putendl_fd.c \
	   ft_putendl.c \
	   ft_putnbr_fd.c \
	   ft_putnbr.c \
	   ft_putstr_fd.c \
	   ft_putstr.c \
	   ft_strcat.c \
	   ft_strchr.c \
	   ft_strclr.c \
	   ft_strcmp.c \
	   ft_strcpy.c \
	   ft_strdel.c \
	   ft_strdup.c \
	   ft_strequ.c \
	   ft_striter.c \
	   ft_striteri.c \
	   ft_strjoin.c \
	   ft_strlcat.c \
	   ft_strlen.c \
	   ft_strmap.c \
	   ft_strmapi.c \
	   ft_strncat.c \
	   ft_strncmp.c \
	   ft_strncpy.c \
	   ft_strnequ.c \
	   ft_strnew.c \
	   ft_strnstr.c \
	   ft_strrchr.c \
	   ft_strsplit.c \
	   ft_strstr.c \
	   ft_strsub.c \
	   ft_strtrim.c \
	   ft_tolower.c \
	   ft_toupper.c \
	   ft_lstnew.c \
	   ft_lstdelone.c \
	   ft_lstdel.c \
	   ft_lstadd.c \
	   ft_lstiter.c \
	   ft_lstmap.c \
	   ft_intlen.c \
	   ft_getnum.c \
	   ft_dupword.c \
	   ft_getwords.c \
	   ft_countwords.c \
	   ft_beg_sp.c ft_end_sp.c \
	   get_next_line.c \
	   $(addprefix ./ft_printf/, ft_printf.c \
	   ft_read_flags.c \
	   ft_upply_options.c \
	   ft_fl_hh.c \
	   ft_fl_h.c \
	   ft_fl_l.c \
	   ft_fl_ll.c \
	   ft_fl_capitll.c \
	   ft_fl_hash.c \
	   ft_conv_csp.c \
	   ft_conv_dibouxf.c \
	   ft_conv_none.c \
	   ft_fl_hash.c \
	   ft_fl_plus.c \
	   ft_fl_sp.c \
	   ft_fl_precision.c \
	   ft_fl_minus.c \
	   ft_fl_zero.c \
	   ft_fl_width.c \
	   ft_ulltoa_base.c \
	   ft_dtoa.c \
	   ft_arandomtoi.c)

OBJ = ft_atoi.o \
	  ft_bzero.o \
	  ft_isalnum.o \
	  ft_isalpha.o \
	  ft_isascii.o \
	  ft_isdigit.o \
	  ft_isprint.o \
	  ft_itoa.o \
	  ft_memalloc.o \
	  ft_memccpy.o \
	  ft_memchr.o \
	  ft_memcmp.o \
	  ft_memcpy.o \
	  ft_memdel.o \
	  ft_memmove.o \
	  ft_memset.o \
	  ft_putchar_fd.o \
	  ft_putchar.o \
	  ft_putendl_fd.o \
	  ft_putendl.o \
	  ft_putnbr_fd.o \
	  ft_putnbr.o \
	  ft_putstr_fd.o \
	  ft_putstr.o \
	  ft_strcat.o \
	  ft_strchr.o \
	  ft_strclr.o \
	  ft_strcmp.o \
	  ft_strcpy.o \
	  ft_strdel.o \
	  ft_strdup.o \
	  ft_strequ.o \
	  ft_striter.o \
	  ft_striteri.o \
	  ft_strjoin.o \
	  ft_strlcat.o \
	  ft_strlen.o \
	  ft_strmap.o \
	  ft_strmapi.o \
	  ft_strncat.o \
	  ft_strncmp.o \
	  ft_strncpy.o \
	  ft_strnequ.o \
	  ft_strnew.o \
	  ft_strnstr.o \
	  ft_strrchr.o \
	  ft_strsplit.o \
	  ft_strstr.o \
	  ft_strsub.o \
	  ft_strtrim.o \
	  ft_tolower.o \
	  ft_toupper.o \
	  ft_lstnew.o \
	  ft_lstdelone.o \
	  ft_lstdel.o \
	  ft_lstadd.o \
	  ft_lstiter.o \
	  ft_lstmap.o \
	  ft_intlen.o \
	  ft_getnum.o \
	  ft_dupword.o \
	  ft_getwords.o \
	  ft_countwords.o \
	  ft_beg_sp.o \
	  ft_end_sp.o \
	  get_next_line.o \
	  ft_printf.o \
	  ft_read_flags.o \
	  ft_upply_options.o \
	  ft_fl_hh.o \
	  ft_fl_h.o \
	  ft_fl_l.o \
	  ft_fl_ll.o \
	  ft_fl_capitll.o \
	  ft_fl_hash.o \
	  ft_conv_csp.o \
	  ft_conv_dibouxf.o \
	  ft_conv_none.o \
	  ft_fl_hash.o \
	  ft_fl_plus.o \
	  ft_fl_sp.o \
	  ft_fl_precision.o \
	  ft_fl_minus.o \
	  ft_fl_zero.o \
	  ft_fl_width.o \
	  ft_ulltoa_base.o \
	  ft_dtoa.o \
	  ft_arandomtoi.o

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -c $(SRCS)
	ar rc $(NAME) $(OBJ)
	ranlib $(NAME)

clean:
	/bin/rm -f $(OBJ)

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
